PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE wine (id integer primary key, name text, price real, purchase_date text, drunk_date text, rating integer, comment text);
INSERT INTO "wine" VALUES(1,'Wirra Wirra McLaren Vale Shiraz','$20','1/1/12','1/1/12',5,'I love Wirra Wirra, everything they produce is delicious.');
INSERT INTO "wine" VALUES(2,'Cakebread Cellars 2010 Chardonnay Napa Valley','$25.99','1/2/12','1/3/12',4,'Pretty good, but not worth the money unless you are a rap star.');
INSERT INTO "wine" VALUES(3,'Franzia Vintner Select Zinfandel','$5.49','1/4/12','1/4/12',3,'It''s in a box, but it is actually pretty good.');
INSERT INTO "wine" VALUES(4,'Big House Wine Company Unchained Chardonnay 2009','$6.00','1/6/12','1/6/12',3,'Meh');
INSERT INTO "wine" VALUES(5,'Big House Red 2009 California','free','1/7/12','1/8/12',3,'Not bad for the price. It''s a good value in the box, a great choice for camping.');
INSERT INTO "wine" VALUES(6,'Save Me SF House of Jupiter Petite Sirah 2011','$12.99','1/9/12','1/9/12',1,'Tastes kind of like you would expect Jupiter to taste like: gross.');
INSERT INTO "wine" VALUES(7,'Save Me, San Francisco Wine Co. Calling All Angels Chardonnay','$4.99','1/20/12','1/21/12',2,'Way too buttery for me, whatever that means.');
CREATE TABLE temp (name text, price real, purchase_date text, drunk_date text, rating integer, comment text);
INSERT INTO "temp" VALUES('Wirra Wirra McLaren Vale Shiraz','$20','1/1/12','1/1/12',5,'I love Wirra Wirra, everything they produce is delicious.');
INSERT INTO "temp" VALUES('Cakebread Cellars 2010 Chardonnay Napa Valley','$25.99','1/2/12','1/3/12',4,'Pretty good, but not worth the money unless you are a rap star.');
INSERT INTO "temp" VALUES('Franzia Vintner Select Zinfandel','$5.49','1/4/12','1/4/12',3,'It''s in a box, but it is actually pretty good.');
INSERT INTO "temp" VALUES('Big House Wine Company Unchained Chardonnay 2009','$6.00','1/6/12','1/6/12',3,'Meh');
INSERT INTO "temp" VALUES('Big House Red 2009 California','free','1/7/12','1/8/12',3,'Not bad for the price. It''s a good value in the box, a great choice for camping.');
INSERT INTO "temp" VALUES('Save Me SF House of Jupiter Petite Sirah 2011','$12.99','1/9/12','1/9/12',1,'Tastes kind of like you would expect Jupiter to taste like: gross.');
INSERT INTO "temp" VALUES('Save Me, San Francisco Wine Co. Calling All Angels Chardonnay','$4.99','1/20/12','1/21/12',2,'Way too buttery for me, whatever that means.');
COMMIT;
